### ISSUE TITLE
Erro 500 ao clicar em pagar.

### ISSUE THREAD

**Issue by blzbruno** [cyberlinux/perfex-crm-pagseguro#1]
Boa noite Allan tudo bem? 

Primeira mente obrigado pela integração livre! 

Estou tentando implementar no meu perfex e estou tendo o seguindo erro a clicar em "Pagar" na página da Fatura, e eu ja inseri os arquivos nos lugares certos e também coloquei o token do pagseguro.

> Esta página não está funcionando nome.meudominio.com.br não consegue atender a esta solicitação no momento.
> HTTP ERROR 500
> 

Qual versão do Perfex você recomenda utilizar sua integração? estou usando a versão 2.1.0.

Abraço,

**Comment by blzbruno** [comment]
Atualizei o meu Perfex para a  Versão 2.2.1 e infelizmente continua dando o mesmo erro, em var/log/apache2/erro.log não encontro nada referente a isso

**Comment by cyberlinux** [comment]
Consegue postar o log de erro para que eu possar entender o problema?

**Comment by blzbruno** [comment]
Descobri que é possivel ativar o modo de desenvolvimento e habilitar a tela de erro, veja.
Estou pesquisando pelo o que possa estar faltando na configuração do meu Perfex.

An uncaught Exception was encountered
Type: Exception

Message: 11033Item description is required.11014senderPhone invalid value: 0

Filename: /var/www/html/lnx/clientes/application/vendor/pagseguro/pagseguro-php-sdk/source/Resources/Responsibility/Http/Methods/Request.php

Line Number: 62

Backtrace:

File: /var/www/html/lnx/clientes/application/vendor/pagseguro/pagseguro-php-sdk/source/Resources/Responsibility/Http/Methods/Success.php
Line: 62
Function: handler

File: /var/www/html/lnx/clientes/application/vendor/pagseguro/pagseguro-php-sdk/source/Resources/Responsibility.php
Line: 67
Function: handler

File: /var/www/html/lnx/clientes/application/vendor/pagseguro/pagseguro-php-sdk/source/Services/Checkout/Payment.php
Line: 71
Function: http

File: /var/www/html/lnx/clientes/application/vendor/pagseguro/pagseguro-php-sdk/source/Domains/Requests/Payment.php
Line: 43
Function: checkout

File: /var/www/html/lnx/clientes/application/libraries/gateways/Pagseguro_gateway.php
Line: 124
Function: register

File: /var/www/html/lnx/clientes/application/libraries/gateways/Pagseguro_gateway.php
Line: 73
Function: create_payment

File: /var/www/html/lnx/clientes/application/models/Payments_model.php
Line: 133
Function: process_payment

File: /var/www/html/lnx/clientes/application/controllers/Invoice.php
Line: 44
Function: process_payment

File: /var/www/html/lnx/clientes/index.php
Line: 319
Function: require_once

**Comment by blzbruno** [comment]
Após eu inserir o numero de telefone da empresa no "perfil da empresa" o erro mudou para:


Type: Exception

**Message: 11033Item description is required.**

Filename: /var/www/html/lnx/clientes/application/vendor/pagseguro/pagseguro-php-sdk/source/Resources/Responsibility/Http/Methods/Request.php

Line Number: 62

Backtrace:

File: /var/www/html/lnx/clientes/application/vendor/pagseguro/pagseguro-php-sdk/source/Resources/Responsibility/Http/Methods/Success.php
Line: 62
Function: handler

File: /var/www/html/lnx/clientes/application/vendor/pagseguro/pagseguro-php-sdk/source/Resources/Responsibility.php
Line: 67
Function: handler

File: /var/www/html/lnx/clientes/application/vendor/pagseguro/pagseguro-php-sdk/source/Services/Checkout/Payment.php
Line: 71
Function: http

File: /var/www/html/lnx/clientes/application/vendor/pagseguro/pagseguro-php-sdk/source/Domains/Requests/Payment.php
Line: 43
Function: checkout

File: /var/www/html/lnx/clientes/application/libraries/gateways/Pagseguro_gateway.php
Line: 124
Function: register

File: /var/www/html/lnx/clientes/application/libraries/gateways/Pagseguro_gateway.php
Line: 73
Function: create_payment

File: /var/www/html/lnx/clientes/application/models/Payments_model.php
Line: 133
Function: process_payment

File: /var/www/html/lnx/clientes/application/controllers/Invoice.php
Line: 44
Function: process_payment

File: /var/www/html/lnx/clientes/index.php
Line: 319
Function: require_once

**Comment by blzbruno** [comment]
Pelo que entendi o erro ocorre pq esta faltando"item description"
[Nesta imagem ](https://imgur.com/a/q70tshj) você pode ver q eu estou inserindo a descrição do item na fatura, o que será que pode estar havendo?

**Comment by blzbruno** [comment]
Ah descobri que estava faltando o "Pagamento da Fatura {invoice_number}" em  Gateway Dashbord Payment Descrição.

**Comment by blzbruno** [comment]
agora deu tudo certo! obrigado!

**Comment by cyberlinux** [comment]
Muito bom, caso encontre mais problemas, estou a disposição.

**Comment by andrelacerda23** [comment]
ola amigo eu estou tendo o mesmo problema acima e já coloquei {invoice_number}" em Gateway Dashbord Payment  e mesmo assim.

**Comment by infotechinfo** [comment]
Estou com mesmo erro, uso versão 2.4.1

**Comment by Buggyfx** [comment]
Sabem dizer se está funcionando com a versao 2.4.4 do Perfex? Pois no meu aqui não funciona.

**Comment by danielbragadasilva** [comment]
Tbm estou tendo o mesmo problema.

**Comment by ELIANAMARCELINOALVES** [comment]
Alguém obteve exito no problema ? Estou também com a versão 2.4.4 instalada e continuo com o erro 500 ao clicar em pagar.

Porém ao colocar em modo desenvolvimento apresenta os seguintes erros php:

Message: add_action is deprecated since version 2.3.0! Use hooks()->add_action($tag, $function_to_add, $priority = 10, $accepted_args = 1) instead.

Filename: helpers/deprecated_helper.php

Line Number: 25


Message: Hook before_add_online_payment_modes is deprecated since version 2.3.0! Use app_payment_gateways instead.

Filename: helpers/deprecated_helper.php

Line Number: 48

**Comment by cronoswebdigital** [comment]
Mesmo erro ao realizar pagamento pelo pagseguro na versão 2.6.0
Esta página não está funcionando nome.meudominio.com.br não consegue atender a esta solicitação no momento.
HTTP ERROR 500
